### ISSUE TITLE
Convert WakeLocker.java  to WakeLocker.kt

### ISSUE THREAD

**Issue by a2krocks** [a2krocks/OnePlus_Weather_Widget#1]
I need help converting WakeLocker.java to WakeLocker.kt so that the full codebase is in kotlin.

Read the guidelines [here](https://github.com/a2krocks/OnePlus_Weather_Widget/blob/master/.github/CONTRIBUTING.md) before starting.

**Comment by shweta-ok99** [comment]
Hi, please assign this to me.

**Comment by a2krocks** [comment]
I have assigned this issue to you. Thanks For your help

**Comment by shweta-ok99** [comment]
Hi

I am unable to push my code. Below is the error message

remote: Permission to a2krocks/OnePlus_Weather_Widget.git denied to
shweta-ok99.
fatal: unable to access '
https://github.com/a2krocks/OnePlus_Weather_Widget.git/': The requested URL
returned error: 403

**Comment by a2krocks** [comment]
Try to create a pull request instead of pushing directly to the repo.

**Comment by a2krocks** [comment]
Create a fork of the repo then make changes there and then create a pull request.

**Comment by shweta-ok99** [comment]
ok

**Comment by shweta-ok99** [comment]
Got it.

**Comment by Mysterious786** [comment]
Assign this to me..

**Comment by a2krocks** [comment]
Okay
